### ISSUE TITLE
Can't seem to run examples successfully

### ISSUE THREAD

**Issue by kgaonkar6** [mikessh/oncofuse#16]
Hello,

I'm trying to run the examples in the repo but the runs are not being completed successfully. Please let me know if I'm doing something wrong? 

Thanks!

The command used:
```
cd target
java -jar oncofuse-1.1.1.jar ../src/main/resources/example/example_starfusion.txt starfusion AVG out.txt
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass$3$1 (file:/Users/gaonkark/Documents/oncofuse/target/oncofuse-1.1.1.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass$3$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[Tue Aug 18 11:51:28 EDT 2020] Loading RefSeq data, assuming hg19
[Tue Aug 18 11:51:29 EDT 2020] Reading input file, assuming STARFUSION format
Ignoring line # Run as java -Xmx4G -jar Oncofuse.jar example_starfusion.txt starfusion AVG out.txt
Ignoring line #fusion_name	JunctionReads	SpanningFrags	LeftGene	LeftBreakpoint	LeftDistFromRefExonSplice	RightGene	RightBreakpoint	RightDistFromRefExonSplice
[Tue Aug 18 11:51:30 EDT 2020] Mapping breakpoints to known genes (this is going to filter a lot)
[Tue Aug 18 11:51:30 EDT 2020] FILTER (reporting first 20 only): Head to head / tail to tail #4 in input
Exception in thread "main" java.lang.AbstractMethodError
	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:231)
	at es.unav.oncofuse.legacy.FpgPart.equals(FpgPart.groovy:60)
	at java.base/java.util.HashMap.putVal(HashMap.java:635)
	at java.base/java.util.HashMap.put(HashMap.java:612)
	at java.base/java.util.HashSet.add(HashSet.java:220)
	at java_util_Set$add$0.call(Unknown Source)
	at es.unav.oncofuse.legacy.Oncofuse$_run_closure20.doCall(Oncofuse.groovy:483)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:272)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:909)
	at groovy.lang.Closure.call(Closure.java:423)
	at groovy.lang.Closure.call(Closure.java:439)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:1373)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:1366)
	at org.codehaus.groovy.runtime.dgm$149.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:271)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at es.unav.oncofuse.legacy.Oncofuse.run(Oncofuse.groovy:433)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1085)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:909)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:901)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:884)
	at org.codehaus.groovy.runtime.InvokerHelper.runScript(InvokerHelper.java:406)
	at org.codehaus.groovy.runtime.InvokerHelper$runScript.callStatic(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:53)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:157)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:169)
	at es.unav.oncofuse.legacy.Oncofuse.main(Oncofuse.groovy)

**Comment by mapostolides** [comment]
I am getting the same output as you. It seems maybe the tool is no longer working or maintained
